### ISSUE TITLE
docdoku-plm-docker/keystore  unexpected character

### ISSUE THREAD

**Issue by 0x0021** [docdoku/docdoku-plm-docker#22]
```bash
 ./start.sh 
Data directory found
/Users/xuyukun/Desktop/docdoku-plm-docker/data
Keystore found
/Users/xuyukun/Desktop/docdoku-plm-docker/keystore
unexpected character "." in variable name near "cluster.name=changeit\nbootstrap.memory_lock=true\ndiscovery.type=single-node\nES_JAVA_OPTS=-Xms512m -Xmx512m"
bash

**Comment by Habanana** [comment]
This was due to `docker compose` not accepting dot in variable name.
And now it's getting fixed. https://github.com/compose-spec/compose-go/pull/271  

I managed to run it by setting variables in docker-compose.yml  

```
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
#    env_file: ./env/es.env
    environment:
      - cluster.name=changeit
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - network    
    volumes:
      - es-volume:/usr/share/elasticsearch/data
```
